mode=rose_arch

[arch]
command-format=foo put %(target)s %(sources)s
source-prefix=/
target-prefix=foo:///hello/worlds/

[arch:planet-n.tar.xz]
source=hello/planet-[1-9].txt

[arch:spaceships/]
compress=xz
source=hello/spaceship-[1-9].txt
